project:
  type: website


website:
  title: "Projet Python"
  open-graph: true
  favicon: content/.img/favicon.png
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    search: true
    left:
      - text: Back to Main Website
        url: https://Alhoer.github.io/
      - file: index.qmd
        text: Home 
      - sidebar:introduction
      - sidebar:discover
      - sidebar:libraries
      - sidebar:advanced_mix
      - sidebar:advanced_mix_2
      - sidebar:projects
    tools:
      - icon: github
        menu:
          - text: Code source
            url:  https://github.com/Alhoer/Projet-Python
            
  sidebar: 
    - id: root
      title: "Projet Python"
      href: index.qmd
    - id: home
      title: "Homepage"
      href: index.qmd
    - id: OrderBook
      title: "Création d'un carnet d'ordre"
      contents: 
      - content/index.qmd
      - content/OrderBook.qmd
        
  repo-url: https://github.com/Alhoer/Projet-Python
  repo-branch: main
  page-footer:
    left: |
      Projet Python, Alban Hoerdt.<br>
      Licence {{< fa brands creative-commons >}}<br>
      Code source disponible sur [`Github`](https://github.com/Alhoer/Projet-Python)
    right: |
      Site construit avec {{< fa brands python >}} et [`Quarto`](https://quarto.org/)<br>
      Inspiration pour la mise en forme du site [ici](https://github.com/linogaliana/python-datascientist)<br>
      [Code source disponible sur {{< fa brands github >}} `GitHub`](https://github.com/Alhoer/Projet-Python)

theme:
  light: flatly
  dark: vapor
format:
  html:
    css: styles.css
    toc: true
    toc-depth: 3
    code-overflow: wrap
format-links: true
author: Alban Hoerdt
date: today
date-format: iso
page-layout: full
google-scholar: true
commentable: true
validate-yaml: false
crossref:
  chapters: true
lightbox: auto
jupyter: python3
