project:
  type: website

website:
  title: "Introduction à Python"
  favicon: /content/.img/favicon.png
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    background: "white"
    search: true
    left:
      - file: index.qmd
        text: Home 
      - sidebar:introduction
      - sidebar:discover
      - sidebar:annexes
    tools:
      - icon: github
        menu:
          - text: Code source
            url:  https://github.com/remigenet/Introduction-Python
  sidebar: 
    - id: home
      title: "Homepage"
      href: index.qmd
    - id: introduction
      title: "Comprendre Et Installer Python"
      contents: 
      - content/Cours_1/1-Histoire.qmd
      - content/Cours_1/2-Python_Execution.qmd
      - content/Cours_1/3-ManyPythons.qmd
      - content/Cours_1/4-Path.qmd
      - content/Cours_1/5-PathandVirtualEnv.qmd
      - content/Cours_1/6-IDEs.qmd
      - content/Cours_1/7-Notebooks.qmd
      - section: Quelques IDEs en Python
        expanded: false
        contents:
        - content/Cours_1/IDEs/VsCode.qmd
        - content/Cours_1/IDEs/Spyder.qmd
        - content/Cours_1/IDEs/Pycharm.qmd
      - section: Travaux Pratiques
        expanded: false
        contents:
        - content/Cours_1/TP-ConstruireSonPython.qmd
      icon: book
    - id: discover 
      title: "Syntaxes et Concepts de Base"
      contents: 
       - content/Cours_2/1-FondamentauxSyntaxique.qmd
       - content/Cours_2/2-FonctionsEtModules.qmd
       - content/Cours_2/3-IntroducingPOOConcept.qmd
    - id: annexes 
      title: "Annexes"
      contents: 
      - content/Annexes/LinuxTerminal.qmd
      - content/Annexes/git_basics.qmd
      - content/Annexes/git_advanced.qmd
        
  repo-url: https://github.com/remigenet/Introduction-Python
  repo-branch: main
  page-footer:
    left: |
      Introduction à Python, Rémi Genet.<br>
      Licence {{< fa brands creative-commons >}}<br>
      Code source disponible sur [`Github`](https://github.com/remigenet/Introduction-Python)
    right: |
      Site construit avec {{< fa brands python >}} et [`Quarto`](https://quarto.org/)<br>
      Inspiration pour la mise en forme du site [ici](https://github.com/linogaliana/python-datascientist)<br>
      [Code source disponible sur {{< fa brands github >}} `GitHub`](https://github.com/remigenet/Introduction-Python)


format:
  html:
    light: sandstone
    dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    code-overflow: wrap
    # embed-resources: true


  
crossref:
  chapters: true

# format-links: true
author: Remi Genet
date: today
date-format: iso
page-layout: article
# title-block-banner: "#e9f3fa"

validate-yaml: false
# jupyter: python3

# wrap: preserve
# cache: true
# keep-ipynb: true



google-scholar: true

commentable: true

# format:
#   html:
#     theme: cosmo
#     css: styles.css
#     toc: true
#     code-overflow: wrap
#     embed-resources: true
  


# date-format: iso
# page-layout: article

# validate-yaml: false
# # jupyter: python3

# wrap: preserve
# keep-ipynb: true