[tool.poetry]
name = "Projet-Python"
version = "0.1.0"
description = ""
authors = ["albanhoerdt <alban.hoerdt@dauphine.eu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
